name: RSS Spider

on:
  schedule:
    - cron: "0 1 * * *"   # 每天 UTC 01:00 运行
  workflow_dispatch:

permissions:
  contents: write   # 允许 Actions 修改代码并 push

jobs:
  run-rss-spider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run spider
        run: python spider_yesterday_matoday.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/*.csv
          git commit -m "Add RSS results for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
